<?php

use App\Http\Controllers\UserController;
use App\Http\Controllers\FotografoController;
use App\Http\Controllers\RedactorController;
use App\Http\Controllers\MunicipioController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\NoticiaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ComentarioController;
use App\Http\Controllers\ImagenController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\SuscripcionController;

Route::get('/usuarios', [UserController::class, 'index']);
Route::get('/usuarios/{id}', [UserController::class, 'show']);
Route::post('/usuarios', [UserController::class, 'store']);
Route::get('/redactores', [RedactorController::class, 'index']);
Route::get('/redactores/{id}', [RedactorController::class, 'show']);
Route::post('/redactores', [RedactorController::class, 'store']);
Route::put('/redactores/{id}', [RedactorController::class, 'update']);
Route::delete('/redactores/{id}', [RedactorController::class, 'destroy']);
Route::get('/fotografos', [FotografoController::class, 'index']);
Route::get('/fotografos/{id}', [FotografoController::class, 'show']);
Route::post('/fotografos', [FotografoController::class, 'store']);
Route::put('/fotografos/{id}', [FotografoController::class, 'update']);
Route::delete('/fotografos/{id}', [FotografoController::class, 'destroy']);
Route::get('/municipios', [MunicipioController::class, 'index']);
Route::get('/municipios/{id}', [MunicipioController::class, 'show']);
Route::post('/municipios', [MunicipioController::class, 'store']);
Route::put('/municipios/{id}', [MunicipioController::class, 'update']);
Route::delete('/municipios/{id}', [MunicipioController::class, 'destroy']);
Route::get('/categorias', [CategoriaController::class, 'index']);
Route::get('/categorias/{id}', [CategoriaController::class, 'show']);
Route::post('/categorias', [CategoriaController::class, 'store']);
Route::put('/categorias/{id}', [CategoriaController::class, 'update']);
Route::delete('/categorias/{id}', [CategoriaController::class, 'destroy']);
Route::get('/noticias', [NoticiaController::class, 'index']);
Route::get('/noticias/{id}', [NoticiaController::class, 'show']);
Route::post('/noticias', [NoticiaController::class, 'store']);
Route::put('/noticias/{id}', [NoticiaController::class, 'update']);
Route::delete('/noticias/{id}', [NoticiaController::class, 'destroy']);
Route::get('/comentarios', [ComentarioController::class, 'index']);
Route::get('/comentarios/{id}', [ComentarioController::class, 'show']);
Route::post('/comentarios', [ComentarioController::class, 'store']);
Route::put('/comentarios/{id}', [ComentarioController::class, 'update']);
Route::delete('/comentarios/{id}', [ComentarioController::class, 'destroy']);
Route::get('/imagenes', [ImagenController::class, 'index']);
Route::get('/imagenes/{id}', [ImagenController::class, 'show']);
Route::post('/imagenes', [ImagenController::class, 'store']);
Route::put('/imagenes/{id}', [ImagenController::class, 'update']);
Route::delete('/imagenes/{id}', [ImagenController::class, 'destroy']);
Route::get('/planes', [PlanController::class, 'index']);
Route::get('/planes/{id}', [PlanController::class, 'show']);
Route::post('/planes', [PlanController::class, 'store']);
Route::put('/planes/{id}', [PlanController::class, 'update']);
Route::delete('/planes/{id}', [PlanController::class, 'destroy']);
Route::get('/suscripciones', [SuscripcionController::class, 'index']);
Route::get('/suscripciones/{id}', [SuscripcionController::class, 'show']);
Route::post('/suscripciones', [SuscripcionController::class, 'store']);
Route::put('/suscripciones/{id}', [SuscripcionController::class, 'update']);
Route::delete('/suscripciones/{id}', [SuscripcionController::class, 'destroy']);